In [117]:
import pandas as pd
import numpy as np
import scipy.stats as st
import plotly.express as px

In [118]:
flights = pd.read_csv('C:/Users/danfv/OneDrive/Knowledge/Courses/Data Analysis/LHL - Data Analysis Bootcamp/lighthouse-data-notes/W6 Midterm Project/Midterm_Project/Data/Flights - Sample 50000 rand.csv').sort_values('fl_date').reset_index(drop=True)
flights = flights.drop('no_name', axis=1)
flights['total_delay'] = flights['carrier_delay'] + flights['weather_delay'] + flights['nas_delay'] + flights['security_delay'] + flights['late_aircraft_delay']
# filling null in total_delay
flights = flights.fillna(value={'total_delay' : 0})

In [119]:
pd.set_option('display.max_columns', None)
flights

,fl_date,mkt_unique_carrier,branded_code_share,mkt_carrier,mkt_carrier_fl_num,op_unique_carrier,tail_num,op_carrier_fl_num,origin_airport_id,origin,origin_city_name,dest_airport_id,dest,dest_city_name,crs_dep_time,dep_time,dep_delay,taxi_out,wheels_off,wheels_on,taxi_in,crs_arr_time,arr_time,arr_delay,cancelled,cancellation_code,diverted,dup,crs_elapsed_time,actual_elapsed_time,air_time,flights,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay,first_dep_time,total_add_gtime,longest_add_gtime,total_delay
0,2018-01-01,DL,DL,DL,260,DL,N964DN,260,14869,SLC,"Salt Lake City, UT",13487,MSP,"Minneapolis, MN",1715,1717.0,2.0,26.0,1743.0,2053.0,3.0,2057,2056.0,-1.0,0,NaN,0,N,162,159.0,130.0,1,991,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1,2018-01-01,UA,UA,UA,2117,UA,N12109,2117,12892,LAX,"Los Angeles, CA",11618,EWR,"Newark, NJ",1200,1150.0,-10.0,18.0,1208.0,1944.0,7.0,2020,1951.0,-29.0,0,NaN,0,N,320,301.0,276.0,1,2454,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
2,2018-01-01,WN,WN,WN,1508,WN,N8306H,1508,13232,MDW,"Chicago, IL",11057,CLT,"Charlotte, NC",1335,1344.0,9.0,15.0,1359.0,1618.0,5.0,1625,1623.0,-2.0,0,NaN,0,N,110,99.0,79.0,1,584,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
3,2018-01-01,NK,NK,NK,967,NK,N639NK,967,11042,CLE,"Cleveland, OH",14635,RSW,"Fort Myers, FL",1520,1520.0,0.0,42.0,1602.0,1824.0,5.0,1805,1829.0,24.0,0,NaN,0,N,165,189.0,142.0,1,1025,0.0,0.0,24.0,0.0,0.0,NaN,NaN,NaN,24.0
4,2018-01-01,NK,NK,NK,467,NK,N525NK,467,10721,BOS,"Boston, MA",13495,MSY,"New Orleans, LA",1420,1414.0,-6.0,16.0,1430.0,1707.0,21.0,1715,1728.0,13.0,0,NaN,0,N,235,254.0,217.0,1,1368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,2019-12-31,AS,AS,AS,1969,AS,N628VA,1969,14679,SAN,"San Diego, CA",14771,SFO,"San Francisco, CA",2040,2039.0,-1.0,23.0,2102.0,2211.0,3.0,2219,2214.0,-5.0,0,NaN,0,N,99,95.0,69.0,1,447,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
49996,2019-12-31,DL,DL_CODESHARE,DL,5502,9E,N8839E,5502,13230,MDT,"Harrisburg, PA",11433,DTW,"Detroit, MI",540,535.0,-5.0,10.0,545.0,654.0,11.0,738,705.0,-33.0,0,NaN,0,N,118,90.0,69.0,1,371,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
49997,2019-12-31,UA,UA_CODESHARE,UA,5445,OO,N962SW,5445,11603,EUG,"Eugene, OR",14771,SFO,"San Francisco, CA",1439,1437.0,-2.0,9.0,1446.0,1552.0,2.0,1624,1554.0,-30.0,0,NaN,0,N,105,77.0,66.0,1,451,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
49998,2019-12-31,WN,WN,WN,3985,WN,N7731A,3985,11292,DEN,"Denver, CO",13198,MCI,"Kansas City, MO",925,926.0,1.0,14.0,940.0,1146.0,3.0,1200,1149.0,-11.0,0,NaN,0,N,95,83.0,66.0,1,533,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
49999,2019-12-31,UA,UA_CODESHARE,UA,3785,ZW,N409AW,3785,13930,ORD,"Chicago, IL",10980,CHA,"Chattanooga, TN",945,940.0,-5.0,39.0,1019.0,1225.0,5.0,1234,1230.0,-4.0,0,NaN,0,N,109,110.0,66.0,1,500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0

# Dropping features absent in testing data:

In [120]:
# Features in training vs testing data
flights_set = set(flights.columns)

# testing data to set:
flights_test = pd.read_csv('C:/Users/danfv/OneDrive/Knowledge/Courses/Data Analysis/LHL - Data Analysis Bootcamp/lighthouse-data-notes/W6 Midterm Project/Midterm_Project/Data/Flights_test - Sample 50000 rand.csv').sort_values('fl_date')
flights_test_set = set(flights_test.columns)

In [121]:
print('Shared features:', flights_set & flights_test_set, sep="\n")
print('In train but not test:', flights_set - flights_test_set, sep="\n")
print('In test but not train empty?:', len(flights_test_set - flights_set) == 0)

Shared features:
{'dup', 'origin_airport_id', 'crs_arr_time', 'crs_elapsed_time', 'op_unique_carrier', 'mkt_carrier_fl_num', 'distance', 'op_carrier_fl_num', 'origin_city_name', 'origin', 'mkt_unique_carrier', 'flights', 'fl_date', 'branded_code_share', 'dest', 'mkt_carrier', 'crs_dep_time', 'dest_airport_id', 'dest_city_name', 'tail_num'}
In train but not test:
{'dep_delay', 'longest_add_gtime', 'taxi_in', 'nas_delay', 'diverted', 'carrier_delay', 'first_dep_time', 'taxi_out', 'air_time', 'arr_time', 'dep_time', 'total_add_gtime', 'late_aircraft_delay', 'security_delay', 'weather_delay', 'cancellation_code', 'arr_delay', 'wheels_on', 'wheels_off', 'cancelled', 'total_delay', 'actual_elapsed_time'}
In test but not train empty?: True

## DF almost as is going to be received in real life:

In [122]:
drop_as_absent = list(flights_set - flights_test_set)
drop_as_absent.remove('total_delay')
flights = flights.drop(columns=drop_list)
flights

,fl_date,mkt_unique_carrier,branded_code_share,mkt_carrier,mkt_carrier_fl_num,op_unique_carrier,tail_num,op_carrier_fl_num,origin_airport_id,origin,origin_city_name,dest_airport_id,dest,dest_city_name,crs_dep_time,crs_arr_time,dup,crs_elapsed_time,flights,distance,total_delay
0,2018-01-01,DL,DL,DL,260,DL,N964DN,260,14869,SLC,"Salt Lake City, UT",13487,MSP,"Minneapolis, MN",1715,2057,N,162,1,991,0.0
1,2018-01-01,UA,UA,UA,2117,UA,N12109,2117,12892,LAX,"Los Angeles, CA",11618,EWR,"Newark, NJ",1200,2020,N,320,1,2454,0.0
2,2018-01-01,WN,WN,WN,1508,WN,N8306H,1508,13232,MDW,"Chicago, IL",11057,CLT,"Charlotte, NC",1335,1625,N,110,1,584,0.0
3,2018-01-01,NK,NK,NK,967,NK,N639NK,967,11042,CLE,"Cleveland, OH",14635,RSW,"Fort Myers, FL",1520,1805,N,165,1,1025,24.0
4,2018-01-01,NK,NK,NK,467,NK,N525NK,467,10721,BOS,"Boston, MA",13495,MSY,"New Orleans, LA",1420,1715,N,235,1,1368,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,2019-12-31,AS,AS,AS,1969,AS,N628VA,1969,14679,SAN,"San Diego, CA",14771,SFO,"San Francisco, CA",2040,2219,N,99,1,447,0.0
49996,2019-12-31,DL,DL_CODESHARE,DL,5502,9E,N8839E,5502,13230,MDT,"Harrisburg, PA",11433,DTW,"Detroit, MI",540,738,N,118,1,371,0.0
49997,2019-12-31,UA,UA_CODESHARE,UA,5445,OO,N962SW,5445,11603,EUG,"Eugene, OR",14771,SFO,"San Francisco, CA",1439,1624,N,105,1,451,0.0
49998,2019-12-31,WN,WN,WN,3985,WN,N7731A,3985,11292,DEN,"Denver, CO",13198,MCI,"Kansas City, MO",925,1200,N,95,1,533,0.0
49999,2019-12-31,UA,UA_CODESHARE,UA,3785,ZW,N409AW,3785,13930,ORD,"Chicago, IL",10980,CHA,"Chattanooga, TN",945,1234,N,109,1,500,0.0

# Dates seasonal fearures:

## Using Date:
- Source: Daniel EDA
- Replaces features: ['fl_date']

In [123]:
# per season
flights['Season'] = ((pd.DatetimeIndex(flights['fl_date']).month)%12 // 3 + 1)

In [124]:
# weekeday
flights['Weekday'] = pd.DatetimeIndex(flights['fl_date']).weekday

In [125]:
# flying season
# https://www.planestats.com/season_2015oct

def is_peak_season(month):
    '''
    Return a number indicating flying season

        Paraneters:
            x(int): month number 1-12
        
        Returns:
            int: 0 for low season, 1 for medium, 2 for high
    '''
    
    if month >= 1 and month <= 2:
        return 0
    elif month >= 3 and month <= 5:
        return 1
    elif month >= 6 and month <= 8:
        return 2
    elif month >= 9 and month <= 11:
        return 0
    else:
        return 1

is_peak_season(12)

flights['month'] = pd.DatetimeIndex(flights['fl_date']).month
flights['peak_season'] = flights['month'].apply(lambda x: is_peak_season(x))

## Using Time of day:
- Source: exploratory analysis task 4
- Replaces: ['crs_dep_time']

In [126]:
# taxi times
hourly_taxi_usage = {0.0: 0.008156744910698958,
    1.0: 0.0027025262535151783,
    2.0: 0.0008600046264541292,
    3.0: 0.0002788768516899051,
    4.0: 0.0023148390695185185,
    5.0: 0.02774663473822249,
    6.0: 0.048601142427888974,
    7.0: 0.05530305289552354,
    8.0: 0.06609300784804596,
    9.0: 0.0623523504240782,
    10.0: 0.05951360975456419,
    11.0: 0.05816597363888349,
    12.0: 0.057866140723193765,
    13.0: 0.05404407705061131,
    14.0: 0.05552470357244471,
    15.0: 0.059419307466565,
    16.0: 0.056478204484436495,
    17.0: 0.06176477462962172,
    18.0: 0.05965869019763986,
    19.0: 0.056196103622900465,
    20.0: 0.0532356565816952,
    21.0: 0.04302602340147547,
    22.0: 0.03243353905202827,
    23.0: 0.01814795142384365,
    24.0: 0.00011606435446053852}

flights['dep_taxi_ind'] = (flights['crs_dep_time'] / 100).apply(np.floor).apply(
    lambda hour: hourly_taxi_usage[hour])

flights['arr_taxi_ind'] = (flights['crs_arr_time'] / 100).apply(np.floor).apply(
    lambda hour: hourly_taxi_usage[hour])

# Carriers Features:
- Source: exploratory_analysis - task 10
- Replaces features: ['mkt_unique_carrier', 'branded_code_share', 'mkt_carrier', 'mkt_carrier_fl_num', 'op_unique_carrier', 'op_carrier_fl_num']

In [127]:
carriers_lateness_ind = {'AA': -0.001449590526739375,
    'DL': -0.01954519343156605,
    'UA': 0.05591569564467608,
    'WN': -0.03725267355189793,
    'AS': -0.025749633447661385,
    'B6': 0.027142308915671882,
    'NK': -0.013690232424457261,
    'F9': 0.0013041744428902644,
    'G4': 0.018603187644906014,
    'HA': -0.00437839621376152,
    'VX': -0.000899647052060779}

flights['carriers_lateness_ind'] = flights['mkt_carrier'].apply(lambda carrier: carriers_lateness_ind[carrier])

# Air time (crs_elapsed_time):
- Source: exploratory analysis Task 8
- Enhances crs_elapsed_time

In [128]:
airtime_ind = {0: 0.21342394833847084,
    1: 0.35026571661163297,
    2: 0.22531183208783437,
    3: 0.10185498550220896,
    4: 0.047492080333921785,
    5: 0.028251636527725693,
    6: 0.024073040816388756,
    7: 0.008076687369085404,
    8: 0.0009939600159765353,
    9: 0.00010061558443934253,
    10: 7.165049194922877e-05,
    11: 3.506300669855876e-05,
    12: 4.878331366756001e-05}


flights['airtime_ind'] = pd.cut(flights.crs_elapsed_time, bins=13, labels=range(13)).apply(
    lambda airtime_bin: airtime_ind[airtime_bin])

# By Airport size:
- Source: Peter's code
- Replaces: ['dest', 'dest_airport_id', 'dest_city_name', 'origin', 'origin_airport_id', 'origin_city_name']

In [133]:
airport_flights_ind = {'ORD': 0.04976,
    'ATL': 0.04904,
    'DFW': 0.03598,
    'DEN': 0.0344,
    'CLT': 0.03218,
    'LAX': 0.03138,
    'SEA': 0.024,
    'DTW': 0.02234,
    'IAH': 0.02232,
    'PHX': 0.0222,
    'SFO': 0.02218,
    'LAS': 0.02098,
    'LGA': 0.0205,
    'EWR': 0.02008,
    'MSP': 0.01992,
    'PHL': 0.01914,
    'BOS': 0.01854,
    'DCA': 0.01814,
    'MCO': 0.01688,
    'JFK': 0.0166,
    'SLC': 0.01512,
    'BWI': 0.01352,
    'FLL': 0.01284,
    'SAN': 0.01276,
    'IAD': 0.01252,
    'MDW': 0.01122,
    'MIA': 0.01078,
    'BNA': 0.01044,
    'PDX': 0.01022,
    'TPA': 0.0099,
    'SJC': 0.00898,
    'STL': 0.00896,
    'DAL': 0.0089,
    'RDU': 0.00842,
    'AUS': 0.00808,
    'HOU': 0.00716,
    'MSY': 0.007,
    'HNL': 0.00698,
    'IND': 0.00696,
    'SMF': 0.00682,
    'CLE': 0.00676,
    'OAK': 0.00674,
    'PIT': 0.00656,
    'CMH': 0.00632,
    'CVG': 0.00628,
    'MCI': 0.00626,
    'SNA': 0.00528,
    'SAT': 0.00524,
    'MKE': 0.0048,
    'JAX': 0.00444,
    'RSW': 0.00422,
    'BUR': 0.00398,
    'BDL': 0.0039,
    'BUF': 0.0039,
    'SDF': 0.00366,
    'OMA': 0.00364,
    'PBI': 0.00364,
    'SJU': 0.00346,
    'ORF': 0.00346,
    'ABQ': 0.00334,
    'MEM': 0.00326,
    'OKC': 0.00326,
    'RNO': 0.00322,
    'ONT': 0.0032,
    'OGG': 0.0032,
    'RIC': 0.00318,
    'BOI': 0.00308,
    'GRR': 0.00298,
    'CHS': 0.00292,
    'GEG': 0.00276,
    'PVD': 0.00268,
    'TYS': 0.00266,
    'ALB': 0.00266,
    'BHM': 0.00254,
    'ANC': 0.00246,
    'SAV': 0.00244,
    'TUS': 0.00242,
    'SYR': 0.00242,
    'GSO': 0.00228,
    'ROC': 0.00226,
    'XNA': 0.0022,
    'LGB': 0.0022,
    'ELP': 0.00216,
    'TUL': 0.00216,
    'DSM': 0.00212,
    'KOA': 0.00198,
    'LIT': 0.00182,
    'FAT': 0.00176,
    'DAY': 0.00176,
    'PWM': 0.00176,
    'GSP': 0.00174,
    'MSN': 0.0016,
    'LIH': 0.00154,
    'LEX': 0.00154,
    'PSP': 0.00154,
    'HSV': 0.0015,
    'SGF': 0.00148,
    'CID': 0.00148,
    'HPN': 0.00144,
    'MYR': 0.00144,
    'BTV': 0.00142,
    'PNS': 0.00134,
    'ILM': 0.00134,
    'ICT': 0.00134,
    'MDT': 0.00134,
    'CAE': 0.00128,
    'MAF': 0.00128,
    'MFR': 0.00126,
    'AVL': 0.00126,
    'MHT': 0.00126,
    'EUG': 0.00122,
    'SBA': 0.00118,
    'CHA': 0.00118,
    'SFB': 0.00112,
    'JAN': 0.0011,
    'CAK': 0.0011,
    'ISP': 0.00108,
    'RDM': 0.00106,
    'COS': 0.00102,
    'AMA': 0.00098,
    'ROA': 0.00098,
    'BTR': 0.00096,
    'LBB': 0.00092,
    'VPS': 0.0009,
    'FSD': 0.0009,
    'PIE': 0.0009,
    'CHO': 0.0009,
    'TLH': 0.00088,
    'MOB': 0.00088,
    'PSC': 0.00088,
    'BIL': 0.00086,
    'PIA': 0.00086,
    'FWA': 0.00086,
    'SRQ': 0.00086,
    'SHV': 0.00086,
    'AGS': 0.00084,
    'SBN': 0.00082,
    'ATW': 0.00082,
    'ASE': 0.00082,
    'LFT': 0.00078,
    'FAR': 0.00078,
    'ECP': 0.00078,
    'EVV': 0.00076,
    'ITO': 0.00074,
    'MGM': 0.00074,
    'MLI': 0.00074,
    'GPT': 0.00072,
    'AZA': 0.00072,
    'PGD': 0.00072,
    'ABE': 0.0007,
    'MRY': 0.0007,
    'SCE': 0.0007,
    'FAI': 0.0007,
    'TVC': 0.00068,
    'RAP': 0.00066,
    'SBP': 0.00066,
    'MFE': 0.00066,
    'EYW': 0.00066,
    'GRB': 0.00064,
    'CRW': 0.00064,
    'BZN': 0.00064,
    'BIS': 0.00064,
    'BGR': 0.00064,
    'MSO': 0.00064,
    'GNV': 0.00064,
    'AZO': 0.00062,
    'AVP': 0.00062,
    'JAC': 0.00062,
    'CRP': 0.00062,
    'FAY': 0.0006,
    'STS': 0.00056,
    'JNU': 0.00056,
    'BLI': 0.00056,
    'DAB': 0.00056,
    'GJT': 0.00054,
    'FCA': 0.00052,
    'RST': 0.00052,
    'DRO': 0.00052,
    'MBS': 0.0005,
    'OAJ': 0.0005,
    'FNT': 0.0005,
    'MLU': 0.0005,
    'TRI': 0.00048,
    'MTJ': 0.00046,
    'TTN': 0.00044,
    'LAN': 0.00044,
    'HRL': 0.00042,
    'GRK': 0.00042,
    'ITH': 0.00042,
    'SGU': 0.00042,
    'SWF': 0.0004,
    'STT': 0.0004,
    'GTF': 0.0004,
    'ACY': 0.00038,
    'KTN': 0.00038,
    'PHF': 0.00038,
    'PAE': 0.00036,
    'HHH': 0.00036,
    'LNK': 0.00036,
    'BFL': 0.00036,
    'HLN': 0.00034,
    'HDN': 0.00034,
    'IDA': 0.00034,
    'CMI': 0.00034,
    'BMI': 0.00032,
    'LRD': 0.00032,
    'CWA': 0.00032,
    'CPR': 0.0003,
    'MOT': 0.00028,
    'COU': 0.00028,
    'LCH': 0.00028,
    'AEX': 0.00028,
    'TOL': 0.00028,
    'TYR': 0.00026,
    'GFK': 0.00026,
    'BRO': 0.00026,
    'ELM': 0.00026,
    'LYH': 0.00026,
    'SBY': 0.00026,
    'CLL': 0.00024,
    'ORH': 0.00024,
    'YKM': 0.00024,
    'EAU': 0.00024,
    'EGE': 0.00024,
    'COD': 0.00024,
    'ACV': 0.00024,
    'EWN': 0.00024,
    'FLG': 0.00024,
    'ISN': 0.00024,
    'LSE': 0.00024,
    'FSM': 0.00024,
    'LNY': 0.00024,
    'MHK': 0.00024,
    'SHD': 0.00022,
    'ABI': 0.00022,
    'DLH': 0.00022,
    'HTS': 0.00022,
    'PUW': 0.0002,
    'ERI': 0.0002,
    'BPT': 0.0002,
    'LWS': 0.0002,
    'RDD': 0.0002,
    'BQN': 0.0002,
    'SLN': 0.0002,
    'CSG': 0.00018,
    'BQK': 0.00018,
    'PGV': 0.00018,
    'JHM': 0.00018,
    'FLO': 0.00018,
    'MLB': 0.00018,
    'SPS': 0.00018,
    'SUN': 0.00018,
    'SIT': 0.00018,
    'LAW': 0.00018,
    'HYS': 0.00018,
    'CGI': 0.00016,
    'IPT': 0.00016,
    'SPI': 0.00016,
    'TWF': 0.00016,
    'PBG': 0.00016,
    'MQT': 0.00016,
    'BGM': 0.00016,
    'HVN': 0.00016,
    'SUX': 0.00016,
    'LCK': 0.00016,
    'SAF': 0.00016,
    'CKB': 0.00014,
    'SCC': 0.00014,
    'VLD': 0.00014,
    'SJT': 0.00014,
    'ACT': 0.00014,
    'ROW': 0.00014,
    'BRW': 0.00014,
    'STX': 0.00014,
    'ACK': 0.00014,
    'YUM': 0.00014,
    'GCC': 0.00014,
    'LAR': 0.00014,
    'DIK': 0.00014,
    'JMS': 0.00014,
    'DBQ': 0.00014,
    'RKS': 0.00012,
    'GRI': 0.00012,
    'SPN': 0.00012,
    'BLV': 0.00012,
    'GUC': 0.00012,
    'EKO': 0.00012,
    'OME': 0.00012,
    'EAT': 0.00012,
    'OTZ': 0.00012,
    'LBE': 0.00012,
    'PSG': 0.00012,
    'CDC': 0.00012,
    'ABY': 0.00012,
    'PIH': 0.00012,
    'PLN': 0.00012,
    'PUB': 0.00012,
    'PQI': 0.00012,
    'DHN': 0.0001,
    'MKK': 0.0001,
    'PRC': 0.0001,
    'MEI': 0.0001,
    'ALO': 0.0001,
    'GTR': 0.0001,
    'PVU': 0.0001,
    'PSE': 0.0001,
    'GUM': 0.0001,
    'LBL': 0.0001,
    'OTH': 0.0001,
    'PAH': 0.0001,
    'USA': 0.0001,
    'IAG': 0.0001,
    'HIB': 8e-05,
    'YAK': 8e-05,
    'IMT': 8e-05,
    'UIN': 8e-05,
    'INL': 8e-05,
    'ATY': 8e-05,
    'BFF': 8e-05,
    'TXK': 8e-05,
    'PIR': 8e-05,
    'CMX': 8e-05,
    'RFD': 8e-05,
    'ESC': 8e-05,
    'BJI': 8e-05,
    'RHI': 8e-05,
    'CIU': 8e-05,
    'BTM': 8e-05,
    'SCK': 8e-05,
    'MKG': 6e-05,
    'LWB': 6e-05,
    'WRG': 6e-05,
    'PIB': 6e-05,
    'JLN': 6e-05,
    'CDV': 6e-05,
    'HOB': 6e-05,
    'DUT': 6e-05,
    'GCK': 6e-05,
    'MVY': 6e-05,
    'ART': 6e-05,
    'ALW': 6e-05,
    'WYS': 4e-05,
    'BKG': 4e-05,
    'MMH': 4e-05,
    'GGG': 4e-05,
    'ADK': 4e-05,
    'LBF': 4e-05,
    'BRD': 4e-05,
    'ABR': 4e-05,
    'SMX': 4e-05,
    'VEL': 2e-05,
    'CNY': 2e-05,
    'XWA': 2e-05,
    'PPG': 2e-05,
    'PSM': 2e-05,
    'EAR': 2e-05,
    'SWO': 2e-05,
    'STC': 2e-05,
    'DRT': 2e-05,
    'HYA': 2e-05,
    'BET': 2e-05,
    'GST': 2e-05,
    'ADQ': 2e-05,
    'OGD': 2e-05,
    'APN': 2e-05}

In [135]:
# creating features with flights volume per airport:
flights['orig_airp_fl_ind'] = flights.origin.apply(lambda origin: airport_flights_ind[origin] if origin in airport_flights_ind.keys() else 0)
flights['dest_airp_fl_ind'] = flights.dest.apply(lambda destin: airport_flights_ind[destin] if destin in airport_flights_ind.keys() else 0)

In [146]:
airport_passen_ind = {'ORD': 0.04211271586825138,
    'ATL': 0.035132785053773576,
    'DFW': 0.023282947249404384,
    'DEN': 0.030771674316557415,
    'CLT': 0.019152813858640788,
    'LAX': 0.028127010620112258,
    'SEA': 0.017266229658245057,
    'DTW': 0.023651218822769306,
    'IAH': 0.024859946428331066,
    'PHX': 0.01658568101974614,
    'SFO': 0.01793654853081717,
    'LAS': 0.015935283270294646,
    'LGA': 0.011639858398503223,
    'EWR': 0.022154442545058082,
    'MSP': 0.023263026126283767,
    'PHL': 0.01716716245137496,
    'BOS': 0.014261908928162814,
    'DCA': 0.010507046424293003,
    'MCO': 0.01624594510922967,
    'JFK': 0.0201924811220438,
    'SLC': 0.013807491957519551,
    'BWI': 0.010323987455076521,
    'FLL': 0.013969014577416446,
    'SAN': 0.008028212617608657,
    'IAD': 0.014227989177984467,
    'MDW': 0.006434522767959297,
    'MIA': 0.02304389377195698,
    'BNA': 0.00836041080586327,
    'PDX': 0.009484608240345659,
    'TPA': 0.009368311954019895,
    'SJC': 0.00536955029410577,
    'STL': 0.00816281480085607,
    'DAL': 0.005142880217517128,
    'RDU': 0.007982986284037527,
    'AUS': 0.007946912898927221,
    'HOU': 0.004791837723607877,
    'MSY': 0.007124224354919037,
    'HNL': 0.005945647638404695,
    'IND': 0.010186154819431172,
    'SMF': 0.0044628699877512015,
    'CLE': 0.006794179801596382,
    'OAK': 0.006780181174538651,
    'PIT': 0.007334203760785,
    'CMH': 0.005341014631257319,
    'CVG': 0.010447821463664141,
    'MCI': 0.007236751780113873,
    'SNA': 0.0025859771445492846,
    'SAT': 0.0062444644852139505,
    'MKE': 0.005461079778714011,
    'JAX': 0.004056371394344016,
    'RSW': 0.004991048954814047,
    'BUR': 0.002800263820279165,
    'BDL': 0.004638929643438817,
    'BUF': 0.0038329317701533117,
    'SDF': 0.0106944126633734,
    'OMA': 0.0041618995060099875,
    'PBI': 0.003552420820265705,
    'SJU': 0.005348013944786185,
    'ORF': 0.0030753906828368755,
    'ABQ': 0.003614876233292504,
    'MEM': 0.015320420497220466,
    'OKC': 0.003533576514611067,
    'RNO': 0.0024799106241503235,
    'ONT': 0.0045161724523171765,
    'OGG': 0.0020012652605225258,
    'RIC': 0.00339035979163582,
    'BOI': 0.0027184256928647382,
    'GRR': 0.003060853647046155,
    'CHS': 0.0030603152383131653,
    'GEG': 0.0025832851008843363,
    'PVD': 0.0026764298116915457,
    'TYS': 0.0024153015761915657,
    'ALB': 0.002497678112338982,
    'BHM': 0.0023576918417616733,
    'ANC': 0.012880890528044364,
    'SAV': 0.002145020392230762,
    'TUS': 0.0021972460393307578,
    'SYR': 0.002883178765159571,
    'GSO': 0.002587053962015264,
    'ROC': 0.002449759735102903,
    'XNA': 0.0016496843578802849,
    'LGB': 0.0009416768739988963,
    'ELP': 0.0027927260980173097,
    'TUL': 0.002886409217557509,
    'DSM': 0.0028611040071069953,
    'KOA': 0.0015059292261720486,
    'LIT': 0.001830589692164807,
    'FAT': 0.0012905657329761889,
    'DAY': 0.002048106820292625,
    'PWM': 0.001812283795243159,
    'GSP': 0.002445452465238986,
    'MSN': 0.002545596489575061,
    'LIH': 0.000846916936992718,
    'LEX': 0.0017972083507194487,
    'PSP': 0.001930195307767892,
    'HSV': 0.001466625388663804,
    'SGF': 0.001153809914796818,
    'CID': 0.0018725855733379997,
    'HPN': 0.0026898900300162867,
    'MYR': 0.0019113510021132544,
    'BTV': 0.0014429354044122595,
    'PNS': 0.001265798931258665,
    'ILM': 0.0007413888253267468,
    'ICT': 0.0019802673199359293,
    'MDT': 0.0018526644502173824,
    'CAE': 0.001594228258382351,
    'MAF': 0.0008856823657679727,
    'MFR': 0.0008544546592545731,
    'AVL': 0.0009018346277576623,
    'MHT': 0.001575922361460703,
    'EUG': 0.0010708949699164121,
    'SBA': 0.000960521179653534,
    'CHA': 0.001011131600554561,
    'SFB': 0.004048295263349172,
    'JAN': 0.0009427536914648755,
    'CAK': 0.0011311967480112527,
    'ISP': 0.000733312694331902,
    'RDM': 0.0005911727888226347,
    'COS': 0.001540387385083386,
    'AMA': 0.0005992489198174795,
    'ROA': 0.0009239093858102378,
    'BTR': 0.0007397735991277779,
    'LBB': 0.0011796535339803212,
    'VPS': 0.0008232269527411734,
    'FSD': 0.001681450473126674,
    'PIE': 0.0029800923370977075,
    'CHO': 0.0007128531624782954,
    'TLH': 0.0008657612426473557,
    'MOB': 0.0005131035225391355,
    'PSC': 0.0007806926628349911,
    'BIL': 0.0013788647651864913,
    'PIA': 0.0009179868897473517,
    'FWA': 0.0010547427079267227,
    'SRQ': 0.0011532715060638284,
    'SHV': 0.001431628821019477,
    'AGS': 0.0005233332884659389,
    'SBN': 0.0011823455776452693,
    'ATW': 0.0009029114452236415,
    'ASE': 0.0004431103872504812,
    'LFT': 0.0006110939119432518,
    'FAR': 0.0014773935633235972,
    'ECP': 0.0006304766263308791,
    'EVV': 0.0005561762211783075,
    'ITO': 0.0003968072362133714,
    'MGM': 0.00042803494272677104,
    'MLI': 0.0009266014294751861,
    'GPT': 0.0018112069777771796,
    'AZA': 0.0023808434172802283,
    'PGD': 0.0012324175898133067,
    'ABE': 0.001255030756598872,
    'MRY': 0.00044903288331336736,
    'SCE': 0.0004484944745803777,
    'FAI': 0.005812660681356252,
    'TVC': 0.000716622023609223,
    'RAP': 0.0008016906034215875,
    'SBP': 0.00035481135504017875,
    'MFE': 0.0008496089806576663,
    'EYW': 0.0005696364395030487,
    'GRB': 0.001020284549015385,
    'CRW': 0.0005771741617649038,
    'BZN': 0.0014703942497947316,
    'BIS': 0.0008092283256834426,
    'BGR': 0.0009685973106483787,
    'MSO': 0.0008264574051391113,
    'GNV': 0.0004323422125906882,
    'AZO': 0.0003838854266216198,
    'AVP': 0.0006471672970535582,
    'JAC': 0.0006433984359226307,
    'CRP': 0.0005227948797329493,
    'FAY': 0.0003962688274803817,
    'STS': 0.0003085082040030689,
    'JNU': 0.003194379012827588,
    'BLI': 0.0007451576864576743,
    'DAB': 0.00035373453757419943,
    'GJT': 0.000722544519672109,
    'FCA': 0.0006390911660587135,
    'RST': 0.0004781069548948084,
    'DRO': 0.00039034633141749557,
    'MBS': 0.00036019544237007525,
    'OAJ': 0.00027943413242162787,
    'FNT': 0.0007284670157349952,
    'MLU': 0.00026597391409688664,
    'TRI': 0.00046841559770099473,
    'MTJ': 0.0004958744430834668,
    'TTN': 0.0007203908847401505,
    'LAN': 0.0007796158453690119,
    'HRL': 0.0006983161266875749,
    'GRK': 0.0003618106685690442,
    'ITH': 0.00021913235432678718,
    'SGU': 0.00021482508446287,
    'SWF': 0.000715006797410254,
    'STT': 0.0010698181524504326,
    'GTF': 0.0007666940357772603,
    'ACY': 0.001184499212577228,
    'KTN': 0.0009196021159463206,
    'PHF': 0.00042965016892574,
    'PAE': 0.0002552057394370937,
    'HHH': 8.722221474432315e-05,
    'LNK': 0.0005944032412205726,
    'BFL': 0.000346735224045334,
    'HLN': 0.0002643586878979177,
    'HDN': 0.00035265772010822016,
    'IDA': 0.00045118651824532595,
    'CMI': 0.00026920436649482455,
    'BMI': 0.0005513305425814006,
    'LRD': 0.0025030621996688786,
    'CWA': 0.0003860390615535784,
    'CPR': 0.0004899519470205806,
    'MOT': 0.0005238716971989286,
    'COU': 0.00033219818825461347,
    'LCH': 0.00018144374301751174,
    'AEX': 0.0009761350329102338,
    'TOL': 0.0005545609949793386,
    'TYR': 0.00011791151252473315,
    'GFK': 0.0005152571574710942,
    'BRO': 0.001032667949874147,
    'ELM': 0.00031927637866286193,
    'LYH': 0.0001512928539700914,
    'SBY': 0.00014213990550926737,
    'CLL': 0.0003763477043597647,
    'ORH': 0.0001480624015721535,
    'YKM': 0.00025897460056802124,
    'EAU': 0.00010498970293298158,
    'EGE': 0.0003731172519618268,
    'COD': 0.0001249108260535986,
    'ACV': 0.00019382714387627367,
    'EWN': 0.00024820642590822823,
    'FLG': 0.00019113510021132542,
    'ISN': 0.00022882371152060086,
    'LSE': 0.00026058982676699014,
    'FSM': 0.00019651918754122193,
    'LNY': 0.00025897460056802124,
    'MHK': 0.0002315157551855491,
    'SHD': 7.968449248246806e-05,
    'ABI': 0.0002611282354999798,
    'DLH': 0.0003693483908308993,
    'HTS': 0.0003758092956267751,
    'PUW': 7.699244881751982e-05,
    'ERI': 0.00020244168360410806,
    'BPT': 8.022290121545772e-05,
    'LWS': 0.00024066870364637314,
    'RDD': 0.00016152261989689474,
    'BQN': 0.0007715397143741671,
    'SLN': 0.0001216803736556607,
    'CSG': 0.000296124803144307,
    'BQK': 6.353223049277859e-05,
    'PGV': 0.00013191013958246402,
    'JHM': 0.00020674895346802524,
    'FLO': 9.09910758752507e-05,
    'MLB': 0.00042372767286285386,
    'SPS': 0.0001556001238340086,
    'SUN': 0.0002665123228298763,
    'SIT': 0.0009734429892452855,
    'LAW': 0.00012760286971854684,
    'HYS': 5.92249606288614e-05,
    'CGI': 5.92249606288614e-05,
    'IPT': 7.968449248246806e-05,
    'SPI': 0.00026597391409688664,
    'TWF': 0.00020674895346802524,
    'PBG': 0.0003488888589772926,
    'MQT': 0.00018252056048349103,
    'BGM': 0.00010660492913195052,
    'HVN': 0.00010983538152988842,
    'SUX': 0.000142678314242257,
    'LCK': 0.0011640396807236213,
    'SAF': 0.00019813441374019085,
    'CKB': 0.0003693483908308993,
    'SCC': 0.0011274278868803251,
    'VLD': 5.276405583298561e-05,
    'SJT': 0.00018790464781338754,
    'ACT': 0.00020405690980307702,
    'ROW': 0.00027243481889276247,
    'BRW': 0.00136540454686175,
    'STX': 0.0004824142247587256,
    'ACK': 0.000744080868991695,
    'YUM': 9.152948460824035e-05,
    'GCC': 8.129971868143702e-05,
    'LAR': 7.268517895360263e-05,
    'DIK': 9.045266714226105e-05,
    'JMS': 7.430040515257157e-05,
    'DBQ': 8.399176234638525e-05,
    'RKS': 9.152948460824035e-05,
    'GRI': 0.00027889572368863824,
    'SPN': 0.0007430040515257158,
    'BLV': 0.0002622050529659591,
    'GUC': 0.00010606652039896087,
    'EKO': 4.845678596906842e-05,
    'OME': 0.004778915914016126,
    'EAT': 0.0001755212469546256,
    'OTZ': 0.004095136823119271,
    'LBE': 0.0002444375647773007,
    'PSG': 0.0003838854266216198,
    'CDC': 0.00011037379026287807,
    'ABY': 0.00020405690980307702,
    'PIH': 0.0001173731037917435,
    'PLN': 0.00013890945311132946,
    'PUB': 0.0001679835246927705,
    'PQI': 0.00010929697279689877,
    'DHN': 0.00011198901646184701,
    'MKK': 0.0002902023070814209,
    'PRC': 7.268517895360263e-05,
    'MEI': 0.0001130658339278263,
    'ALO': 0.00010983538152988842,
    'GTR': 0.00011198901646184701,
    'PVU': 0.00022020917179276647,
    'PSE': 0.00011198901646184701,
    'GUM': 0.0018112069777771796,
    'LBL': 7.537722261855088e-05,
    'OTH': 0.00027351163635874173,
    'PAH': 6.783950035669579e-05,
    'USA': 0.0002557441481700833,
    'IAG': 0.00032627569219172733,
    'HIB': 7.753085755050947e-05,
    'YAK': 0.00033165977952162384,
    'IMT': 0.00011145060772885736,
    'UIN': 5.0610420901027016e-05,
    'INL': 7.591563135154053e-05,
    'ATY': 4.9533603435047714e-05,
    'BFF': 0.00018790464781338754,
    'TXK': 9.206789334123e-05,
    'PIR': 0.00013621740944638123,
    'CMX': 0.00015883057623194649,
    'RFD': 0.001617379833900906,
    'ESC': 9.368311954019894e-05,
    'BJI': 0.00022667007658864227,
    'RHI': 9.852879813710578e-05,
    'CIU': 0.00010337447673401262,
    'BTM': 5.384087329896491e-05,
    'SCK': 0.000265435505363897,
    'MKG': 0.00010175925053504368,
    'LWB': 0.00011198901646184701,
    'WRG': 0.00026812754902884523,
    'PIB': 0.00011037379026287807,
    'JLN': 0.00010445129419999193,
    'CDV': 0.00036450271223399243,
    'HOB': 6.407063922576824e-05,
    'DUT': 0.0005863271102257278,
    'GCK': 0.0001206035561896814,
    'MVY': 0.00044580243091542945,
    'ART': 4.8995194702058066e-05,
    'ALW': 3.8765428775254735e-05,
    'WYS': 1.4537035790720526e-05,
    'BKG': 7.753085755050947e-05,
    'MMH': 7.968449248246806e-05,
    'GGG': 0.00011468106012679526,
    'ADK': 0.00010068243306906438,
    'LBF': 0.00016098421116390508,
    'BRD': 0.00017229079455668772,
    'ABR': 0.00010014402433607474,
    'SMX': 0.0001556001238340086,
    'VEL': 6.622427415772684e-05,
    'CNY': 5.653291696391315e-05,
    'XWA': 9.09910758752507e-05,
    'PPG': 0.00021536349319585963,
    'PSM': 0.0002368998425154456,
    'EAR': 0.0001184499212577228,
    'SWO': 9.691357193813684e-05,
    'STC': 9.422152827318859e-05,
    'DRT': 0.00013352536578143298,
    'HYA': 0.0002422839298453421,
    'BET': 0.011503102580323853,
    'GST': 0.0005556378124453178,
    'ADQ': 0.001755212469546256,
    'OGD': 9.152948460824035e-05,
    'APN': 0.00010175925053504368}

In [147]:
# creating features with passengers volume per airport:
flights['orig_airp_pss_ind'] = flights.origin.apply(lambda origin: airport_passen_ind[origin] if origin in airport_passen_ind.keys() else 0)
flights['dest_airp_pss_ind'] = flights.dest.apply(lambda destin: airport_passen_ind[destin] if destin in airport_passen_ind.keys() else 0)

# END RESULT:

In [151]:
flights

,fl_date,mkt_unique_carrier,branded_code_share,mkt_carrier,mkt_carrier_fl_num,op_unique_carrier,tail_num,op_carrier_fl_num,origin_airport_id,origin,origin_city_name,dest_airport_id,dest,dest_city_name,crs_dep_time,crs_arr_time,dup,crs_elapsed_time,flights,distance,total_delay,Season,Weekday,month,peak_season,dep_taxi_ind,arr_taxi_ind,carriers_lateness_ind,airtime_ind,orig_airp_fl_ind,dest_airp_fl_ind,orig_airp_pss_ind,dest_airp_pss_ind
0,2018-01-01,DL,DL,DL,260,DL,N964DN,260,14869,SLC,"Salt Lake City, UT",13487,MSP,"Minneapolis, MN",1715,2057,N,162,1,991,0.0,1,0,1,0,0.061765,0.053236,-0.019545,0.225312,0.01512,0.01992,0.013807,0.023263
1,2018-01-01,UA,UA,UA,2117,UA,N12109,2117,12892,LAX,"Los Angeles, CA",11618,EWR,"Newark, NJ",1200,2020,N,320,1,2454,0.0,1,0,1,0,0.057866,0.053236,0.055916,0.028252,0.03138,0.02008,0.028127,0.022154
2,2018-01-01,WN,WN,WN,1508,WN,N8306H,1508,13232,MDW,"Chicago, IL",11057,CLT,"Charlotte, NC",1335,1625,N,110,1,584,0.0,1,0,1,0,0.054044,0.056478,-0.037253,0.350266,0.01122,0.03218,0.006435,0.019153
3,2018-01-01,NK,NK,NK,967,NK,N639NK,967,11042,CLE,"Cleveland, OH",14635,RSW,"Fort Myers, FL",1520,1805,N,165,1,1025,24.0,1,0,1,0,0.059419,0.059659,-0.013690,0.225312,0.00676,0.00422,0.006794,0.004991
4,2018-01-01,NK,NK,NK,467,NK,N525NK,467,10721,BOS,"Boston, MA",13495,MSY,"New Orleans, LA",1420,1715,N,235,1,1368,0.0,1,0,1,0,0.055525,0.061765,-0.013690,0.047492,0.01854,0.00700,0.014262,0.007124
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,2019-12-31,AS,AS,AS,1969,AS,N628VA,1969,14679,SAN,"San Diego, CA",14771,SFO,"San Francisco, CA",2040,2219,N,99,1,447,0.0,1,1,12,1,0.053236,0.032434,-0.025750,0.350266,0.01276,0.02218,0.008028,0.017937
49996,2019-12-31,DL,DL_CODESHARE,DL,5502,9E,N8839E,5502,13230,MDT,"Harrisburg, PA",11433,DTW,"Detroit, MI",540,738,N,118,1,371,0.0,1,1,12,1,0.027747,0.055303,-0.019545,0.350266,0.00134,0.02234,0.001853,0.023651
49997,2019-12-31,UA,UA_CODESHARE,UA,5445,OO,N962SW,5445,11603,EUG,"Eugene, OR",14771,SFO,"San Francisco, CA",1439,1624,N,105,1,451,0.0,1,1,12,1,0.055525,0.056478,0.055916,0.350266,0.00122,0.02218,0.001071,0.017937
49998,2019-12-31,WN,WN,WN,3985,WN,N7731A,3985,11292,DEN,"Denver, CO",13198,MCI,"Kansas City, MO",925,1200,N,95,1,533,0.0,1,1,12,1,0.062352,0.057866,-0.037253,0.350266,0.03440,0.00626,0.030772,0.007237
49999,2019-12-31,UA,UA_CODESHARE,UA,3785,ZW,N409AW,3785,13930,ORD,"Chicago, IL",10980,CHA,"Chattanooga, TN",945,1234,N,109,1,500,0.0,1,1,12,1,0.062352,0.057866,0.055916,0.350266,0.04976,0.00118,0.042113,0.001011

In [149]:
drop_engineered_dan = ['fl_date', 'month', 'crs_dep_time', 'crs_arr_time', 'mkt_unique_carrier', 'branded_code_share',
    'mkt_carrier', 'mkt_carrier_fl_num', 'op_unique_carrier', 'op_carrier_fl_num']

drop_engineered_peter = ['dest', 'dest_airport_id', 'dest_city_name', 'origin', 'origin_airport_id', 'origin_city_name']

drop_streamlining = ['dup', 'flights', 'tail_num']

original_remain = ['crs_elapsed_time', 'distance']

initial_columns_set = set(flights.columns)
drop_dan_set = set(drop_engineered_dan)
prop_peter_set = set(drop_engineered_peter)
drop_streamlining = set(drop_streamlining)
initial_columns_set - drop_dan_set - prop_peter_set - drop_streamlining

{'Season',
 'Weekday',
 'airtime_ind',
 'arr_taxi_ind',
 'carriers_lateness_ind',
 'crs_elapsed_time',
 'dep_taxi_ind',
 'dest_airp_fl_ind',
 'dest_airp_pss_ind',
 'distance',
 'orig_airp_fl_ind',
 'orig_airp_pss_ind',
 'peak_season',
 'total_delay'}

In [152]:
flights.to_csv('Data/Flights - Sample 50000 - Added Dan Features.csv')